version: '3.8'

services:
  # 1. API Gateway
  api-gateway:
    build: ./api-gateway
    image: dangkiman/api-gateway:latest
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    env_file:
      - .env  
    depends_on:
      - product-service
      - auth-service

  # 2. Product Service
  product-service:
    build: 
      context: ./product-service
      args:
        - PRODUCT_SERVICE_PORT=${PRODUCT_SERVICE_PORT}
        - DATABASE_URL=${DATABASE_URL}
        - DIRECT_URL=${DIRECT_URL}

    image: dangkiman/product-service:latest
    
    container_name: product-service
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    env_file:
      - .env  
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

      
  # 3. Auth Service
  auth-service:
    build: 
      context: ./auth-service
      args:
        - DATABASE_URL=${DATABASE_URL}
        - DIRECT_URL=${DIRECT_URL}
    image: dangkiman/auth-service:latest
    
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
      - 51212:51212
    env_file:
      - .env  

  order-service:
    build: 
      context: ./order-service 
    image: dangkiman/order-service:latest
    container_name: order-service
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}" 
    env_file:
      - .env 
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"